version: '3.1'

volumes:
  telegram-logging-bot-data:

services:
  telegram-logging-bot:
    image: bogdandm/telegramloggingbot
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - CONFIG_PATH=./config_docker.json
    environment:
      - TELEGRAM_TOKEN=/run/secrets/telegram-logging-bot-token
      - TELEGRAM_ACCESS_PASSWORD=/run/secrets/telegram-logging-bot-password
    volumes:
      - telegram-logging-bot-data:/opt/telegram-logging-bot-data
    working_dir: /opt/telegram-logging-bot-data
    container_name: telegram-logging-bot
    # links:
    #   - "redis:redis"
    # depends_on:
    #   - "redis"
    entrypoint: python -m telegram_logging.bot
    secrets:
      - telegram-logging-bot-token
      - telegram-logging-bot-password

secrets:
  telegram-logging-bot-token:
    file: ~/docker-secrets/telegram-logging-bot-token
  telegram-logging-bot-password:
    file: ~/docker-secrets/telegram-logging-bot-password
